version: '3.9'

services: 
  postgres:
    image: docker.io/postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mai_backend-2022