// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DatGuyDied/2022-mai-backend-novikov/ent/predicate"
	"github.com/DatGuyDied/2022-mai-backend-novikov/ent/usermessage"
)

// UserMessageQuery is the builder for querying UserMessage entities.
type UserMessageQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserMessageQuery builder.
func (umq *UserMessageQuery) Where(ps ...predicate.UserMessage) *UserMessageQuery {
	umq.predicates = append(umq.predicates, ps...)
	return umq
}

// Limit adds a limit step to the query.
func (umq *UserMessageQuery) Limit(limit int) *UserMessageQuery {
	umq.limit = &limit
	return umq
}

// Offset adds an offset step to the query.
func (umq *UserMessageQuery) Offset(offset int) *UserMessageQuery {
	umq.offset = &offset
	return umq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (umq *UserMessageQuery) Unique(unique bool) *UserMessageQuery {
	umq.unique = &unique
	return umq
}

// Order adds an order step to the query.
func (umq *UserMessageQuery) Order(o ...OrderFunc) *UserMessageQuery {
	umq.order = append(umq.order, o...)
	return umq
}

// First returns the first UserMessage entity from the query.
// Returns a *NotFoundError when no UserMessage was found.
func (umq *UserMessageQuery) First(ctx context.Context) (*UserMessage, error) {
	nodes, err := umq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usermessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (umq *UserMessageQuery) FirstX(ctx context.Context) *UserMessage {
	node, err := umq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserMessage ID from the query.
// Returns a *NotFoundError when no UserMessage ID was found.
func (umq *UserMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usermessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (umq *UserMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := umq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserMessage entity is found.
// Returns a *NotFoundError when no UserMessage entities are found.
func (umq *UserMessageQuery) Only(ctx context.Context) (*UserMessage, error) {
	nodes, err := umq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usermessage.Label}
	default:
		return nil, &NotSingularError{usermessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (umq *UserMessageQuery) OnlyX(ctx context.Context) *UserMessage {
	node, err := umq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserMessage ID in the query.
// Returns a *NotSingularError when more than one UserMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (umq *UserMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = &NotSingularError{usermessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (umq *UserMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := umq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserMessages.
func (umq *UserMessageQuery) All(ctx context.Context) ([]*UserMessage, error) {
	if err := umq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return umq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (umq *UserMessageQuery) AllX(ctx context.Context) []*UserMessage {
	nodes, err := umq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserMessage IDs.
func (umq *UserMessageQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := umq.Select(usermessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (umq *UserMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := umq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (umq *UserMessageQuery) Count(ctx context.Context) (int, error) {
	if err := umq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return umq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (umq *UserMessageQuery) CountX(ctx context.Context) int {
	count, err := umq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (umq *UserMessageQuery) Exist(ctx context.Context) (bool, error) {
	if err := umq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return umq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (umq *UserMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := umq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (umq *UserMessageQuery) Clone() *UserMessageQuery {
	if umq == nil {
		return nil
	}
	return &UserMessageQuery{
		config:     umq.config,
		limit:      umq.limit,
		offset:     umq.offset,
		order:      append([]OrderFunc{}, umq.order...),
		predicates: append([]predicate.UserMessage{}, umq.predicates...),
		// clone intermediate query.
		sql:    umq.sql.Clone(),
		path:   umq.path,
		unique: umq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserMessage.Query().
//		GroupBy(usermessage.FieldFrom).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (umq *UserMessageQuery) GroupBy(field string, fields ...string) *UserMessageGroupBy {
	group := &UserMessageGroupBy{config: umq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := umq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return umq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//	}
//
//	client.UserMessage.Query().
//		Select(usermessage.FieldFrom).
//		Scan(ctx, &v)
//
func (umq *UserMessageQuery) Select(fields ...string) *UserMessageSelect {
	umq.fields = append(umq.fields, fields...)
	return &UserMessageSelect{UserMessageQuery: umq}
}

func (umq *UserMessageQuery) prepareQuery(ctx context.Context) error {
	for _, f := range umq.fields {
		if !usermessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if umq.path != nil {
		prev, err := umq.path(ctx)
		if err != nil {
			return err
		}
		umq.sql = prev
	}
	return nil
}

func (umq *UserMessageQuery) sqlAll(ctx context.Context) ([]*UserMessage, error) {
	var (
		nodes = []*UserMessage{}
		_spec = umq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserMessage{config: umq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, umq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (umq *UserMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := umq.querySpec()
	_spec.Node.Columns = umq.fields
	if len(umq.fields) > 0 {
		_spec.Unique = umq.unique != nil && *umq.unique
	}
	return sqlgraph.CountNodes(ctx, umq.driver, _spec)
}

func (umq *UserMessageQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := umq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (umq *UserMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usermessage.Table,
			Columns: usermessage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usermessage.FieldID,
			},
		},
		From:   umq.sql,
		Unique: true,
	}
	if unique := umq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := umq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermessage.FieldID)
		for i := range fields {
			if fields[i] != usermessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := umq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := umq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := umq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := umq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (umq *UserMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(umq.driver.Dialect())
	t1 := builder.Table(usermessage.Table)
	columns := umq.fields
	if len(columns) == 0 {
		columns = usermessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if umq.sql != nil {
		selector = umq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if umq.unique != nil && *umq.unique {
		selector.Distinct()
	}
	for _, p := range umq.predicates {
		p(selector)
	}
	for _, p := range umq.order {
		p(selector)
	}
	if offset := umq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := umq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserMessageGroupBy is the group-by builder for UserMessage entities.
type UserMessageGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (umgb *UserMessageGroupBy) Aggregate(fns ...AggregateFunc) *UserMessageGroupBy {
	umgb.fns = append(umgb.fns, fns...)
	return umgb
}

// Scan applies the group-by query and scans the result into the given value.
func (umgb *UserMessageGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := umgb.path(ctx)
	if err != nil {
		return err
	}
	umgb.sql = query
	return umgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (umgb *UserMessageGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := umgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(umgb.fields) > 1 {
		return nil, errors.New("ent: UserMessageGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := umgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (umgb *UserMessageGroupBy) StringsX(ctx context.Context) []string {
	v, err := umgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = umgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (umgb *UserMessageGroupBy) StringX(ctx context.Context) string {
	v, err := umgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(umgb.fields) > 1 {
		return nil, errors.New("ent: UserMessageGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := umgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (umgb *UserMessageGroupBy) IntsX(ctx context.Context) []int {
	v, err := umgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = umgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (umgb *UserMessageGroupBy) IntX(ctx context.Context) int {
	v, err := umgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(umgb.fields) > 1 {
		return nil, errors.New("ent: UserMessageGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := umgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (umgb *UserMessageGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := umgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = umgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (umgb *UserMessageGroupBy) Float64X(ctx context.Context) float64 {
	v, err := umgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(umgb.fields) > 1 {
		return nil, errors.New("ent: UserMessageGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := umgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (umgb *UserMessageGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := umgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (umgb *UserMessageGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = umgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (umgb *UserMessageGroupBy) BoolX(ctx context.Context) bool {
	v, err := umgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (umgb *UserMessageGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range umgb.fields {
		if !usermessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := umgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (umgb *UserMessageGroupBy) sqlQuery() *sql.Selector {
	selector := umgb.sql.Select()
	aggregation := make([]string, 0, len(umgb.fns))
	for _, fn := range umgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(umgb.fields)+len(umgb.fns))
		for _, f := range umgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(umgb.fields...)...)
}

// UserMessageSelect is the builder for selecting fields of UserMessage entities.
type UserMessageSelect struct {
	*UserMessageQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ums *UserMessageSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ums.prepareQuery(ctx); err != nil {
		return err
	}
	ums.sql = ums.UserMessageQuery.sqlQuery(ctx)
	return ums.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ums *UserMessageSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ums.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ums.fields) > 1 {
		return nil, errors.New("ent: UserMessageSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ums.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ums *UserMessageSelect) StringsX(ctx context.Context) []string {
	v, err := ums.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ums.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ums *UserMessageSelect) StringX(ctx context.Context) string {
	v, err := ums.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ums.fields) > 1 {
		return nil, errors.New("ent: UserMessageSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ums.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ums *UserMessageSelect) IntsX(ctx context.Context) []int {
	v, err := ums.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ums.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ums *UserMessageSelect) IntX(ctx context.Context) int {
	v, err := ums.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ums.fields) > 1 {
		return nil, errors.New("ent: UserMessageSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ums.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ums *UserMessageSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ums.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ums.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ums *UserMessageSelect) Float64X(ctx context.Context) float64 {
	v, err := ums.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ums.fields) > 1 {
		return nil, errors.New("ent: UserMessageSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ums.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ums *UserMessageSelect) BoolsX(ctx context.Context) []bool {
	v, err := ums.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ums *UserMessageSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ums.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usermessage.Label}
	default:
		err = fmt.Errorf("ent: UserMessageSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ums *UserMessageSelect) BoolX(ctx context.Context) bool {
	v, err := ums.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ums *UserMessageSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ums.sql.Query()
	if err := ums.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
