// Code generated by entc, DO NOT EDIT.

package usermessage

import (
	"time"
)

const (
	// Label holds the string label denoting the usermessage type in the database.
	Label = "user_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFrom holds the string denoting the from field in the database.
	FieldFrom = "from"
	// FieldTo holds the string denoting the to field in the database.
	FieldTo = "to"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldCtreatedAt holds the string denoting the ctreated_at field in the database.
	FieldCtreatedAt = "ctreated_at"
	// Table holds the table name of the usermessage in the database.
	Table = "user_messages"
)

// Columns holds all SQL columns for usermessage fields.
var Columns = []string{
	FieldID,
	FieldFrom,
	FieldTo,
	FieldText,
	FieldCtreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCtreatedAt holds the default value on creation for the "ctreated_at" field.
	DefaultCtreatedAt func() time.Time
)
